/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebRouteRouteImport } from './routes/_web/route'
import { Route as WebIndexRouteImport } from './routes/_web/index'
import { Route as WebAlumniRouteImport } from './routes/_web/alumni'
import { Route as WebEMarketRouteImport } from './routes/_web/e-market'
import { Route as WebFreshmenRouteImport } from './routes/_web/freshmen'
import { Route as WebKnhHubRouteImport } from './routes/_web/knh-hub'
import { Route as WebQrcodeRouteImport } from './routes/_web/qrcode'
import { Route as WebRegisterRouteImport } from './routes/_web/register'
import { Route as WebYellowPagesRouteImport } from './routes/_web/yellow-pages'
import { Route as AdminAdminRouteRouteImport } from './routes/admin/_admin/route'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as SellerSellerRouteRouteImport } from './routes/seller/_seller/route'
import { Route as SellerLoginRouteImport } from './routes/seller/login'
import { Route as SellerRegisterRouteImport } from './routes/seller/register'
import { Route as StudentStudentRouteRouteImport } from './routes/student/_student/route'
import { Route as StudentForgotPinRouteImport } from './routes/student/forgot-pin'
import { Route as StudentLoginRouteImport } from './routes/student/login'
import { Route as AdminAdminIndexRouteImport } from './routes/admin/_admin/index'
import { Route as AdminAdminAccountRouteImport } from './routes/admin/_admin/account'
import { Route as AdminAdminReportsRouteImport } from './routes/admin/_admin/reports'
import { Route as PrintInventoryRequestIdRouteImport } from './routes/print/inventory/$requestId'
import { Route as PrintRepairsRequestIdRouteImport } from './routes/print/repairs/$requestId'
import { Route as SellerSellerIndexRouteImport } from './routes/seller/_seller/index'
import { Route as SellerSellerAccountRouteImport } from './routes/seller/_seller/account'
import { Route as SellerSellerAnalyticsRouteImport } from './routes/seller/_seller/analytics'
import { Route as SellerSellerBillingRouteImport } from './routes/seller/_seller/billing'
import { Route as SellerSellerMenuRouteImport } from './routes/seller/_seller/menu'
import { Route as SellerSellerProductsRouteImport } from './routes/seller/_seller/products'
import { Route as StudentStudentIndexRouteImport } from './routes/student/_student/index'
import { Route as StudentStudentProfileRouteImport } from './routes/student/_student/profile'
import { Route as StudentStudentSuggestionsRouteImport } from './routes/student/_student/suggestions'
import { Route as AdminAdminAlumniIndexRouteImport } from './routes/admin/_admin/alumni/index'
import { Route as AdminAdminEMarketIndexRouteImport } from './routes/admin/_admin/e-market/index'
import { Route as AdminAdminFreshmenIndexRouteImport } from './routes/admin/_admin/freshmen/index'
import { Route as AdminAdminHubIndexRouteImport } from './routes/admin/_admin/hub/index'
import { Route as AdminAdminInventoryIndexRouteImport } from './routes/admin/_admin/inventory/index'
import { Route as AdminAdminOrdersIndexRouteImport } from './routes/admin/_admin/orders/index'
import { Route as AdminAdminRepairsIndexRouteImport } from './routes/admin/_admin/repairs/index'
import { Route as AdminAdminRepairsRequestIdRouteImport } from './routes/admin/_admin/repairs/$requestId'
import { Route as AdminAdminRoomsIndexRouteImport } from './routes/admin/_admin/rooms/index'
import { Route as AdminAdminRoomsUploadRouteImport } from './routes/admin/_admin/rooms/upload'
import { Route as AdminAdminSellersIndexRouteImport } from './routes/admin/_admin/sellers/index'
import { Route as AdminAdminSellersSellerIdRouteImport } from './routes/admin/_admin/sellers/$sellerId'
import { Route as AdminAdminStaffIndexRouteImport } from './routes/admin/_admin/staff/index'
import { Route as AdminAdminStaffStaffIdRouteImport } from './routes/admin/_admin/staff/$staffId'
import { Route as AdminAdminStaffNewRouteImport } from './routes/admin/_admin/staff/new'
import { Route as AdminAdminStudentsIndexRouteImport } from './routes/admin/_admin/students/index'
import { Route as AdminAdminStudentsStudentIdRouteImport } from './routes/admin/_admin/students/$studentId'
import { Route as AdminAdminSuggestionsIndexRouteImport } from './routes/admin/_admin/suggestions/index'
import { Route as AdminAdminYellowPagesIndexRouteImport } from './routes/admin/_admin/yellow-pages/index'
import { Route as StudentStudentOrdersIndexRouteImport } from './routes/student/_student/orders/index'
import { Route as StudentStudentOrdersNewRouteImport } from './routes/student/_student/orders/new'
import { Route as StudentStudentRepairsIndexRouteImport } from './routes/student/_student/repairs/index'
import { Route as StudentStudentRepairsNewRouteImport } from './routes/student/_student/repairs/new'

const WebRouteRoute = WebRouteRouteImport.update({
  id: '/_web',
  getParentRoute: () => rootRouteImport,
} as any)
const WebIndexRoute = WebIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebAlumniRoute = WebAlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebEMarketRoute = WebEMarketRouteImport.update({
  id: '/e-market',
  path: '/e-market',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebFreshmenRoute = WebFreshmenRouteImport.update({
  id: '/freshmen',
  path: '/freshmen',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebKnhHubRoute = WebKnhHubRouteImport.update({
  id: '/knh-hub',
  path: '/knh-hub',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebQrcodeRoute = WebQrcodeRouteImport.update({
  id: '/qrcode',
  path: '/qrcode',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebRegisterRoute = WebRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebYellowPagesRoute = WebYellowPagesRouteImport.update({
  id: '/yellow-pages',
  path: '/yellow-pages',
  getParentRoute: () => WebRouteRoute,
} as any)
const AdminAdminRouteRoute = AdminAdminRouteRouteImport.update({
  id: '/admin/_admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSellerRouteRoute = SellerSellerRouteRouteImport.update({
  id: '/seller/_seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerLoginRoute = SellerLoginRouteImport.update({
  id: '/seller/login',
  path: '/seller/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRegisterRoute = SellerRegisterRouteImport.update({
  id: '/seller/register',
  path: '/seller/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStudentRouteRoute = StudentStudentRouteRouteImport.update({
  id: '/student/_student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentForgotPinRoute = StudentForgotPinRouteImport.update({
  id: '/student/forgot-pin',
  path: '/student/forgot-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminAccountRoute = AdminAdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const PrintInventoryRequestIdRoute = PrintInventoryRequestIdRouteImport.update({
  id: '/print/inventory/$requestId',
  path: '/print/inventory/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRepairsRequestIdRoute = PrintRepairsRequestIdRouteImport.update({
  id: '/print/repairs/$requestId',
  path: '/print/repairs/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSellerIndexRoute = SellerSellerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerSellerRouteRoute,
} as any)
const SellerSellerAccountRoute = SellerSellerAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SellerSellerRouteRoute,
} as any)
const SellerSellerAnalyticsRoute = SellerSellerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SellerSellerRouteRoute,
} as any)
const SellerSellerBillingRoute = SellerSellerBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SellerSellerRouteRoute,
} as any)
const SellerSellerMenuRoute = SellerSellerMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => SellerSellerRouteRoute,
} as any)
const SellerSellerProductsRoute = SellerSellerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SellerSellerRouteRoute,
} as any)
const StudentStudentIndexRoute = StudentStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentStudentRouteRoute,
} as any)
const StudentStudentProfileRoute = StudentStudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentStudentRouteRoute,
} as any)
const StudentStudentSuggestionsRoute =
  StudentStudentSuggestionsRouteImport.update({
    id: '/suggestions',
    path: '/suggestions',
    getParentRoute: () => StudentStudentRouteRoute,
  } as any)
const AdminAdminAlumniIndexRoute = AdminAdminAlumniIndexRouteImport.update({
  id: '/alumni/',
  path: '/alumni/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminEMarketIndexRoute = AdminAdminEMarketIndexRouteImport.update({
  id: '/e-market/',
  path: '/e-market/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminFreshmenIndexRoute = AdminAdminFreshmenIndexRouteImport.update({
  id: '/freshmen/',
  path: '/freshmen/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminHubIndexRoute = AdminAdminHubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminInventoryIndexRoute =
  AdminAdminInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AdminAdminRouteRoute,
  } as any)
const AdminAdminOrdersIndexRoute = AdminAdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminRepairsIndexRoute = AdminAdminRepairsIndexRouteImport.update({
  id: '/repairs/',
  path: '/repairs/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminRepairsRequestIdRoute =
  AdminAdminRepairsRequestIdRouteImport.update({
    id: '/repairs/$requestId',
    path: '/repairs/$requestId',
    getParentRoute: () => AdminAdminRouteRoute,
  } as any)
const AdminAdminRoomsIndexRoute = AdminAdminRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminRoomsUploadRoute = AdminAdminRoomsUploadRouteImport.update({
  id: '/rooms/upload',
  path: '/rooms/upload',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminSellersIndexRoute = AdminAdminSellersIndexRouteImport.update({
  id: '/sellers/',
  path: '/sellers/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminSellersSellerIdRoute =
  AdminAdminSellersSellerIdRouteImport.update({
    id: '/sellers/$sellerId',
    path: '/sellers/$sellerId',
    getParentRoute: () => AdminAdminRouteRoute,
  } as any)
const AdminAdminStaffIndexRoute = AdminAdminStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminStaffStaffIdRoute = AdminAdminStaffStaffIdRouteImport.update({
  id: '/staff/$staffId',
  path: '/staff/$staffId',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminStaffNewRoute = AdminAdminStaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminStudentsIndexRoute = AdminAdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminStudentsStudentIdRoute =
  AdminAdminStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AdminAdminRouteRoute,
  } as any)
const AdminAdminSuggestionsIndexRoute =
  AdminAdminSuggestionsIndexRouteImport.update({
    id: '/suggestions/',
    path: '/suggestions/',
    getParentRoute: () => AdminAdminRouteRoute,
  } as any)
const AdminAdminYellowPagesIndexRoute =
  AdminAdminYellowPagesIndexRouteImport.update({
    id: '/yellow-pages/',
    path: '/yellow-pages/',
    getParentRoute: () => AdminAdminRouteRoute,
  } as any)
const StudentStudentOrdersIndexRoute =
  StudentStudentOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => StudentStudentRouteRoute,
  } as any)
const StudentStudentOrdersNewRoute = StudentStudentOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => StudentStudentRouteRoute,
} as any)
const StudentStudentRepairsIndexRoute =
  StudentStudentRepairsIndexRouteImport.update({
    id: '/repairs/',
    path: '/repairs/',
    getParentRoute: () => StudentStudentRouteRoute,
  } as any)
const StudentStudentRepairsNewRoute =
  StudentStudentRepairsNewRouteImport.update({
    id: '/repairs/new',
    path: '/repairs/new',
    getParentRoute: () => StudentStudentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WebIndexRoute
  '/admin': typeof AdminAdminRouteRouteWithChildren
  '/seller': typeof SellerSellerRouteRouteWithChildren
  '/student': typeof StudentStudentRouteRouteWithChildren
  '/alumni': typeof WebAlumniRoute
  '/e-market': typeof WebEMarketRoute
  '/freshmen': typeof WebFreshmenRoute
  '/knh-hub': typeof WebKnhHubRoute
  '/qrcode': typeof WebQrcodeRoute
  '/register': typeof WebRegisterRoute
  '/yellow-pages': typeof WebYellowPagesRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/seller/login': typeof SellerLoginRoute
  '/seller/register': typeof SellerRegisterRoute
  '/student/forgot-pin': typeof StudentForgotPinRoute
  '/student/login': typeof StudentLoginRoute
  '/admin/account': typeof AdminAdminAccountRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/print/inventory/$requestId': typeof PrintInventoryRequestIdRoute
  '/print/repairs/$requestId': typeof PrintRepairsRequestIdRoute
  '/seller/account': typeof SellerSellerAccountRoute
  '/seller/analytics': typeof SellerSellerAnalyticsRoute
  '/seller/billing': typeof SellerSellerBillingRoute
  '/seller/menu': typeof SellerSellerMenuRoute
  '/seller/products': typeof SellerSellerProductsRoute
  '/student/profile': typeof StudentStudentProfileRoute
  '/student/suggestions': typeof StudentStudentSuggestionsRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/seller/': typeof SellerSellerIndexRoute
  '/student/': typeof StudentStudentIndexRoute
  '/admin/repairs/$requestId': typeof AdminAdminRepairsRequestIdRoute
  '/admin/rooms/upload': typeof AdminAdminRoomsUploadRoute
  '/admin/sellers/$sellerId': typeof AdminAdminSellersSellerIdRoute
  '/admin/staff/$staffId': typeof AdminAdminStaffStaffIdRoute
  '/admin/staff/new': typeof AdminAdminStaffNewRoute
  '/admin/students/$studentId': typeof AdminAdminStudentsStudentIdRoute
  '/student/orders/new': typeof StudentStudentOrdersNewRoute
  '/student/repairs/new': typeof StudentStudentRepairsNewRoute
  '/admin/alumni/': typeof AdminAdminAlumniIndexRoute
  '/admin/e-market/': typeof AdminAdminEMarketIndexRoute
  '/admin/freshmen/': typeof AdminAdminFreshmenIndexRoute
  '/admin/hub/': typeof AdminAdminHubIndexRoute
  '/admin/inventory/': typeof AdminAdminInventoryIndexRoute
  '/admin/orders/': typeof AdminAdminOrdersIndexRoute
  '/admin/repairs/': typeof AdminAdminRepairsIndexRoute
  '/admin/rooms/': typeof AdminAdminRoomsIndexRoute
  '/admin/sellers/': typeof AdminAdminSellersIndexRoute
  '/admin/staff/': typeof AdminAdminStaffIndexRoute
  '/admin/students/': typeof AdminAdminStudentsIndexRoute
  '/admin/suggestions/': typeof AdminAdminSuggestionsIndexRoute
  '/admin/yellow-pages/': typeof AdminAdminYellowPagesIndexRoute
  '/student/orders/': typeof StudentStudentOrdersIndexRoute
  '/student/repairs/': typeof StudentStudentRepairsIndexRoute
}
export interface FileRoutesByTo {
  '/alumni': typeof WebAlumniRoute
  '/e-market': typeof WebEMarketRoute
  '/freshmen': typeof WebFreshmenRoute
  '/knh-hub': typeof WebKnhHubRoute
  '/qrcode': typeof WebQrcodeRoute
  '/register': typeof WebRegisterRoute
  '/yellow-pages': typeof WebYellowPagesRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/seller/login': typeof SellerLoginRoute
  '/seller/register': typeof SellerRegisterRoute
  '/student/forgot-pin': typeof StudentForgotPinRoute
  '/student/login': typeof StudentLoginRoute
  '/': typeof WebIndexRoute
  '/admin/account': typeof AdminAdminAccountRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/print/inventory/$requestId': typeof PrintInventoryRequestIdRoute
  '/print/repairs/$requestId': typeof PrintRepairsRequestIdRoute
  '/seller/account': typeof SellerSellerAccountRoute
  '/seller/analytics': typeof SellerSellerAnalyticsRoute
  '/seller/billing': typeof SellerSellerBillingRoute
  '/seller/menu': typeof SellerSellerMenuRoute
  '/seller/products': typeof SellerSellerProductsRoute
  '/student/profile': typeof StudentStudentProfileRoute
  '/student/suggestions': typeof StudentStudentSuggestionsRoute
  '/admin': typeof AdminAdminIndexRoute
  '/seller': typeof SellerSellerIndexRoute
  '/student': typeof StudentStudentIndexRoute
  '/admin/repairs/$requestId': typeof AdminAdminRepairsRequestIdRoute
  '/admin/rooms/upload': typeof AdminAdminRoomsUploadRoute
  '/admin/sellers/$sellerId': typeof AdminAdminSellersSellerIdRoute
  '/admin/staff/$staffId': typeof AdminAdminStaffStaffIdRoute
  '/admin/staff/new': typeof AdminAdminStaffNewRoute
  '/admin/students/$studentId': typeof AdminAdminStudentsStudentIdRoute
  '/student/orders/new': typeof StudentStudentOrdersNewRoute
  '/student/repairs/new': typeof StudentStudentRepairsNewRoute
  '/admin/alumni': typeof AdminAdminAlumniIndexRoute
  '/admin/e-market': typeof AdminAdminEMarketIndexRoute
  '/admin/freshmen': typeof AdminAdminFreshmenIndexRoute
  '/admin/hub': typeof AdminAdminHubIndexRoute
  '/admin/inventory': typeof AdminAdminInventoryIndexRoute
  '/admin/orders': typeof AdminAdminOrdersIndexRoute
  '/admin/repairs': typeof AdminAdminRepairsIndexRoute
  '/admin/rooms': typeof AdminAdminRoomsIndexRoute
  '/admin/sellers': typeof AdminAdminSellersIndexRoute
  '/admin/staff': typeof AdminAdminStaffIndexRoute
  '/admin/students': typeof AdminAdminStudentsIndexRoute
  '/admin/suggestions': typeof AdminAdminSuggestionsIndexRoute
  '/admin/yellow-pages': typeof AdminAdminYellowPagesIndexRoute
  '/student/orders': typeof StudentStudentOrdersIndexRoute
  '/student/repairs': typeof StudentStudentRepairsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_web': typeof WebRouteRouteWithChildren
  '/admin/_admin': typeof AdminAdminRouteRouteWithChildren
  '/seller/_seller': typeof SellerSellerRouteRouteWithChildren
  '/student/_student': typeof StudentStudentRouteRouteWithChildren
  '/_web/alumni': typeof WebAlumniRoute
  '/_web/e-market': typeof WebEMarketRoute
  '/_web/freshmen': typeof WebFreshmenRoute
  '/_web/knh-hub': typeof WebKnhHubRoute
  '/_web/qrcode': typeof WebQrcodeRoute
  '/_web/register': typeof WebRegisterRoute
  '/_web/yellow-pages': typeof WebYellowPagesRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/seller/login': typeof SellerLoginRoute
  '/seller/register': typeof SellerRegisterRoute
  '/student/forgot-pin': typeof StudentForgotPinRoute
  '/student/login': typeof StudentLoginRoute
  '/_web/': typeof WebIndexRoute
  '/admin/_admin/account': typeof AdminAdminAccountRoute
  '/admin/_admin/reports': typeof AdminAdminReportsRoute
  '/print/inventory/$requestId': typeof PrintInventoryRequestIdRoute
  '/print/repairs/$requestId': typeof PrintRepairsRequestIdRoute
  '/seller/_seller/account': typeof SellerSellerAccountRoute
  '/seller/_seller/analytics': typeof SellerSellerAnalyticsRoute
  '/seller/_seller/billing': typeof SellerSellerBillingRoute
  '/seller/_seller/menu': typeof SellerSellerMenuRoute
  '/seller/_seller/products': typeof SellerSellerProductsRoute
  '/student/_student/profile': typeof StudentStudentProfileRoute
  '/student/_student/suggestions': typeof StudentStudentSuggestionsRoute
  '/admin/_admin/': typeof AdminAdminIndexRoute
  '/seller/_seller/': typeof SellerSellerIndexRoute
  '/student/_student/': typeof StudentStudentIndexRoute
  '/admin/_admin/repairs/$requestId': typeof AdminAdminRepairsRequestIdRoute
  '/admin/_admin/rooms/upload': typeof AdminAdminRoomsUploadRoute
  '/admin/_admin/sellers/$sellerId': typeof AdminAdminSellersSellerIdRoute
  '/admin/_admin/staff/$staffId': typeof AdminAdminStaffStaffIdRoute
  '/admin/_admin/staff/new': typeof AdminAdminStaffNewRoute
  '/admin/_admin/students/$studentId': typeof AdminAdminStudentsStudentIdRoute
  '/student/_student/orders/new': typeof StudentStudentOrdersNewRoute
  '/student/_student/repairs/new': typeof StudentStudentRepairsNewRoute
  '/admin/_admin/alumni/': typeof AdminAdminAlumniIndexRoute
  '/admin/_admin/e-market/': typeof AdminAdminEMarketIndexRoute
  '/admin/_admin/freshmen/': typeof AdminAdminFreshmenIndexRoute
  '/admin/_admin/hub/': typeof AdminAdminHubIndexRoute
  '/admin/_admin/inventory/': typeof AdminAdminInventoryIndexRoute
  '/admin/_admin/orders/': typeof AdminAdminOrdersIndexRoute
  '/admin/_admin/repairs/': typeof AdminAdminRepairsIndexRoute
  '/admin/_admin/rooms/': typeof AdminAdminRoomsIndexRoute
  '/admin/_admin/sellers/': typeof AdminAdminSellersIndexRoute
  '/admin/_admin/staff/': typeof AdminAdminStaffIndexRoute
  '/admin/_admin/students/': typeof AdminAdminStudentsIndexRoute
  '/admin/_admin/suggestions/': typeof AdminAdminSuggestionsIndexRoute
  '/admin/_admin/yellow-pages/': typeof AdminAdminYellowPagesIndexRoute
  '/student/_student/orders/': typeof StudentStudentOrdersIndexRoute
  '/student/_student/repairs/': typeof StudentStudentRepairsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/seller'
    | '/student'
    | '/alumni'
    | '/e-market'
    | '/freshmen'
    | '/knh-hub'
    | '/qrcode'
    | '/register'
    | '/yellow-pages'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/api/$'
    | '/seller/login'
    | '/seller/register'
    | '/student/forgot-pin'
    | '/student/login'
    | '/admin/account'
    | '/admin/reports'
    | '/print/inventory/$requestId'
    | '/print/repairs/$requestId'
    | '/seller/account'
    | '/seller/analytics'
    | '/seller/billing'
    | '/seller/menu'
    | '/seller/products'
    | '/student/profile'
    | '/student/suggestions'
    | '/admin/'
    | '/seller/'
    | '/student/'
    | '/admin/repairs/$requestId'
    | '/admin/rooms/upload'
    | '/admin/sellers/$sellerId'
    | '/admin/staff/$staffId'
    | '/admin/staff/new'
    | '/admin/students/$studentId'
    | '/student/orders/new'
    | '/student/repairs/new'
    | '/admin/alumni/'
    | '/admin/e-market/'
    | '/admin/freshmen/'
    | '/admin/hub/'
    | '/admin/inventory/'
    | '/admin/orders/'
    | '/admin/repairs/'
    | '/admin/rooms/'
    | '/admin/sellers/'
    | '/admin/staff/'
    | '/admin/students/'
    | '/admin/suggestions/'
    | '/admin/yellow-pages/'
    | '/student/orders/'
    | '/student/repairs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/alumni'
    | '/e-market'
    | '/freshmen'
    | '/knh-hub'
    | '/qrcode'
    | '/register'
    | '/yellow-pages'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/api/$'
    | '/seller/login'
    | '/seller/register'
    | '/student/forgot-pin'
    | '/student/login'
    | '/'
    | '/admin/account'
    | '/admin/reports'
    | '/print/inventory/$requestId'
    | '/print/repairs/$requestId'
    | '/seller/account'
    | '/seller/analytics'
    | '/seller/billing'
    | '/seller/menu'
    | '/seller/products'
    | '/student/profile'
    | '/student/suggestions'
    | '/admin'
    | '/seller'
    | '/student'
    | '/admin/repairs/$requestId'
    | '/admin/rooms/upload'
    | '/admin/sellers/$sellerId'
    | '/admin/staff/$staffId'
    | '/admin/staff/new'
    | '/admin/students/$studentId'
    | '/student/orders/new'
    | '/student/repairs/new'
    | '/admin/alumni'
    | '/admin/e-market'
    | '/admin/freshmen'
    | '/admin/hub'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/repairs'
    | '/admin/rooms'
    | '/admin/sellers'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/suggestions'
    | '/admin/yellow-pages'
    | '/student/orders'
    | '/student/repairs'
  id:
    | '__root__'
    | '/_web'
    | '/admin/_admin'
    | '/seller/_seller'
    | '/student/_student'
    | '/_web/alumni'
    | '/_web/e-market'
    | '/_web/freshmen'
    | '/_web/knh-hub'
    | '/_web/qrcode'
    | '/_web/register'
    | '/_web/yellow-pages'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/api/$'
    | '/seller/login'
    | '/seller/register'
    | '/student/forgot-pin'
    | '/student/login'
    | '/_web/'
    | '/admin/_admin/account'
    | '/admin/_admin/reports'
    | '/print/inventory/$requestId'
    | '/print/repairs/$requestId'
    | '/seller/_seller/account'
    | '/seller/_seller/analytics'
    | '/seller/_seller/billing'
    | '/seller/_seller/menu'
    | '/seller/_seller/products'
    | '/student/_student/profile'
    | '/student/_student/suggestions'
    | '/admin/_admin/'
    | '/seller/_seller/'
    | '/student/_student/'
    | '/admin/_admin/repairs/$requestId'
    | '/admin/_admin/rooms/upload'
    | '/admin/_admin/sellers/$sellerId'
    | '/admin/_admin/staff/$staffId'
    | '/admin/_admin/staff/new'
    | '/admin/_admin/students/$studentId'
    | '/student/_student/orders/new'
    | '/student/_student/repairs/new'
    | '/admin/_admin/alumni/'
    | '/admin/_admin/e-market/'
    | '/admin/_admin/freshmen/'
    | '/admin/_admin/hub/'
    | '/admin/_admin/inventory/'
    | '/admin/_admin/orders/'
    | '/admin/_admin/repairs/'
    | '/admin/_admin/rooms/'
    | '/admin/_admin/sellers/'
    | '/admin/_admin/staff/'
    | '/admin/_admin/students/'
    | '/admin/_admin/suggestions/'
    | '/admin/_admin/yellow-pages/'
    | '/student/_student/orders/'
    | '/student/_student/repairs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WebRouteRoute: typeof WebRouteRouteWithChildren
  AdminAdminRouteRoute: typeof AdminAdminRouteRouteWithChildren
  SellerSellerRouteRoute: typeof SellerSellerRouteRouteWithChildren
  StudentStudentRouteRoute: typeof StudentStudentRouteRouteWithChildren
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  SellerLoginRoute: typeof SellerLoginRoute
  SellerRegisterRoute: typeof SellerRegisterRoute
  StudentForgotPinRoute: typeof StudentForgotPinRoute
  StudentLoginRoute: typeof StudentLoginRoute
  PrintInventoryRequestIdRoute: typeof PrintInventoryRequestIdRoute
  PrintRepairsRequestIdRoute: typeof PrintRepairsRequestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_web': {
      id: '/_web'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WebRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web/': {
      id: '/_web/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebIndexRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/alumni': {
      id: '/_web/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof WebAlumniRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/e-market': {
      id: '/_web/e-market'
      path: '/e-market'
      fullPath: '/e-market'
      preLoaderRoute: typeof WebEMarketRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/freshmen': {
      id: '/_web/freshmen'
      path: '/freshmen'
      fullPath: '/freshmen'
      preLoaderRoute: typeof WebFreshmenRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/knh-hub': {
      id: '/_web/knh-hub'
      path: '/knh-hub'
      fullPath: '/knh-hub'
      preLoaderRoute: typeof WebKnhHubRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/qrcode': {
      id: '/_web/qrcode'
      path: '/qrcode'
      fullPath: '/qrcode'
      preLoaderRoute: typeof WebQrcodeRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/register': {
      id: '/_web/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof WebRegisterRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/yellow-pages': {
      id: '/_web/yellow-pages'
      path: '/yellow-pages'
      fullPath: '/yellow-pages'
      preLoaderRoute: typeof WebYellowPagesRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/_seller': {
      id: '/seller/_seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerSellerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/login': {
      id: '/seller/login'
      path: '/seller/login'
      fullPath: '/seller/login'
      preLoaderRoute: typeof SellerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/register': {
      id: '/seller/register'
      path: '/seller/register'
      fullPath: '/seller/register'
      preLoaderRoute: typeof SellerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/_student': {
      id: '/student/_student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentStudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/forgot-pin': {
      id: '/student/forgot-pin'
      path: '/student/forgot-pin'
      fullPath: '/student/forgot-pin'
      preLoaderRoute: typeof StudentForgotPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin/': {
      id: '/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/account': {
      id: '/admin/_admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAdminAccountRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/reports': {
      id: '/admin/_admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/print/inventory/$requestId': {
      id: '/print/inventory/$requestId'
      path: '/print/inventory/$requestId'
      fullPath: '/print/inventory/$requestId'
      preLoaderRoute: typeof PrintInventoryRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/repairs/$requestId': {
      id: '/print/repairs/$requestId'
      path: '/print/repairs/$requestId'
      fullPath: '/print/repairs/$requestId'
      preLoaderRoute: typeof PrintRepairsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/_seller/': {
      id: '/seller/_seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerSellerIndexRouteImport
      parentRoute: typeof SellerSellerRouteRoute
    }
    '/seller/_seller/account': {
      id: '/seller/_seller/account'
      path: '/account'
      fullPath: '/seller/account'
      preLoaderRoute: typeof SellerSellerAccountRouteImport
      parentRoute: typeof SellerSellerRouteRoute
    }
    '/seller/_seller/analytics': {
      id: '/seller/_seller/analytics'
      path: '/analytics'
      fullPath: '/seller/analytics'
      preLoaderRoute: typeof SellerSellerAnalyticsRouteImport
      parentRoute: typeof SellerSellerRouteRoute
    }
    '/seller/_seller/billing': {
      id: '/seller/_seller/billing'
      path: '/billing'
      fullPath: '/seller/billing'
      preLoaderRoute: typeof SellerSellerBillingRouteImport
      parentRoute: typeof SellerSellerRouteRoute
    }
    '/seller/_seller/menu': {
      id: '/seller/_seller/menu'
      path: '/menu'
      fullPath: '/seller/menu'
      preLoaderRoute: typeof SellerSellerMenuRouteImport
      parentRoute: typeof SellerSellerRouteRoute
    }
    '/seller/_seller/products': {
      id: '/seller/_seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerSellerProductsRouteImport
      parentRoute: typeof SellerSellerRouteRoute
    }
    '/student/_student/': {
      id: '/student/_student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentStudentIndexRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
    '/student/_student/profile': {
      id: '/student/_student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentStudentProfileRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
    '/student/_student/suggestions': {
      id: '/student/_student/suggestions'
      path: '/suggestions'
      fullPath: '/student/suggestions'
      preLoaderRoute: typeof StudentStudentSuggestionsRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
    '/admin/_admin/alumni/': {
      id: '/admin/_admin/alumni/'
      path: '/alumni'
      fullPath: '/admin/alumni/'
      preLoaderRoute: typeof AdminAdminAlumniIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/e-market/': {
      id: '/admin/_admin/e-market/'
      path: '/e-market'
      fullPath: '/admin/e-market/'
      preLoaderRoute: typeof AdminAdminEMarketIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/freshmen/': {
      id: '/admin/_admin/freshmen/'
      path: '/freshmen'
      fullPath: '/admin/freshmen/'
      preLoaderRoute: typeof AdminAdminFreshmenIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/hub/': {
      id: '/admin/_admin/hub/'
      path: '/hub'
      fullPath: '/admin/hub/'
      preLoaderRoute: typeof AdminAdminHubIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/inventory/': {
      id: '/admin/_admin/inventory/'
      path: '/inventory'
      fullPath: '/admin/inventory/'
      preLoaderRoute: typeof AdminAdminInventoryIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/orders/': {
      id: '/admin/_admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminAdminOrdersIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/repairs/': {
      id: '/admin/_admin/repairs/'
      path: '/repairs'
      fullPath: '/admin/repairs/'
      preLoaderRoute: typeof AdminAdminRepairsIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/repairs/$requestId': {
      id: '/admin/_admin/repairs/$requestId'
      path: '/repairs/$requestId'
      fullPath: '/admin/repairs/$requestId'
      preLoaderRoute: typeof AdminAdminRepairsRequestIdRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/rooms/': {
      id: '/admin/_admin/rooms/'
      path: '/rooms'
      fullPath: '/admin/rooms/'
      preLoaderRoute: typeof AdminAdminRoomsIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/rooms/upload': {
      id: '/admin/_admin/rooms/upload'
      path: '/rooms/upload'
      fullPath: '/admin/rooms/upload'
      preLoaderRoute: typeof AdminAdminRoomsUploadRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/sellers/': {
      id: '/admin/_admin/sellers/'
      path: '/sellers'
      fullPath: '/admin/sellers/'
      preLoaderRoute: typeof AdminAdminSellersIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/sellers/$sellerId': {
      id: '/admin/_admin/sellers/$sellerId'
      path: '/sellers/$sellerId'
      fullPath: '/admin/sellers/$sellerId'
      preLoaderRoute: typeof AdminAdminSellersSellerIdRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/staff/': {
      id: '/admin/_admin/staff/'
      path: '/staff'
      fullPath: '/admin/staff/'
      preLoaderRoute: typeof AdminAdminStaffIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/staff/$staffId': {
      id: '/admin/_admin/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/admin/staff/$staffId'
      preLoaderRoute: typeof AdminAdminStaffStaffIdRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/staff/new': {
      id: '/admin/_admin/staff/new'
      path: '/staff/new'
      fullPath: '/admin/staff/new'
      preLoaderRoute: typeof AdminAdminStaffNewRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/students/': {
      id: '/admin/_admin/students/'
      path: '/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AdminAdminStudentsIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/students/$studentId': {
      id: '/admin/_admin/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AdminAdminStudentsStudentIdRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/suggestions/': {
      id: '/admin/_admin/suggestions/'
      path: '/suggestions'
      fullPath: '/admin/suggestions/'
      preLoaderRoute: typeof AdminAdminSuggestionsIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/yellow-pages/': {
      id: '/admin/_admin/yellow-pages/'
      path: '/yellow-pages'
      fullPath: '/admin/yellow-pages/'
      preLoaderRoute: typeof AdminAdminYellowPagesIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/student/_student/orders/': {
      id: '/student/_student/orders/'
      path: '/orders'
      fullPath: '/student/orders/'
      preLoaderRoute: typeof StudentStudentOrdersIndexRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
    '/student/_student/orders/new': {
      id: '/student/_student/orders/new'
      path: '/orders/new'
      fullPath: '/student/orders/new'
      preLoaderRoute: typeof StudentStudentOrdersNewRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
    '/student/_student/repairs/': {
      id: '/student/_student/repairs/'
      path: '/repairs'
      fullPath: '/student/repairs/'
      preLoaderRoute: typeof StudentStudentRepairsIndexRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
    '/student/_student/repairs/new': {
      id: '/student/_student/repairs/new'
      path: '/repairs/new'
      fullPath: '/student/repairs/new'
      preLoaderRoute: typeof StudentStudentRepairsNewRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
  }
}

interface WebRouteRouteChildren {
  WebAlumniRoute: typeof WebAlumniRoute
  WebEMarketRoute: typeof WebEMarketRoute
  WebFreshmenRoute: typeof WebFreshmenRoute
  WebKnhHubRoute: typeof WebKnhHubRoute
  WebQrcodeRoute: typeof WebQrcodeRoute
  WebRegisterRoute: typeof WebRegisterRoute
  WebYellowPagesRoute: typeof WebYellowPagesRoute
  WebIndexRoute: typeof WebIndexRoute
}

const WebRouteRouteChildren: WebRouteRouteChildren = {
  WebAlumniRoute: WebAlumniRoute,
  WebEMarketRoute: WebEMarketRoute,
  WebFreshmenRoute: WebFreshmenRoute,
  WebKnhHubRoute: WebKnhHubRoute,
  WebQrcodeRoute: WebQrcodeRoute,
  WebRegisterRoute: WebRegisterRoute,
  WebYellowPagesRoute: WebYellowPagesRoute,
  WebIndexRoute: WebIndexRoute,
}

const WebRouteRouteWithChildren = WebRouteRoute._addFileChildren(
  WebRouteRouteChildren,
)

interface AdminAdminRouteRouteChildren {
  AdminAdminAccountRoute: typeof AdminAdminAccountRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminRepairsRequestIdRoute: typeof AdminAdminRepairsRequestIdRoute
  AdminAdminRoomsUploadRoute: typeof AdminAdminRoomsUploadRoute
  AdminAdminSellersSellerIdRoute: typeof AdminAdminSellersSellerIdRoute
  AdminAdminStaffStaffIdRoute: typeof AdminAdminStaffStaffIdRoute
  AdminAdminStaffNewRoute: typeof AdminAdminStaffNewRoute
  AdminAdminStudentsStudentIdRoute: typeof AdminAdminStudentsStudentIdRoute
  AdminAdminAlumniIndexRoute: typeof AdminAdminAlumniIndexRoute
  AdminAdminEMarketIndexRoute: typeof AdminAdminEMarketIndexRoute
  AdminAdminFreshmenIndexRoute: typeof AdminAdminFreshmenIndexRoute
  AdminAdminHubIndexRoute: typeof AdminAdminHubIndexRoute
  AdminAdminInventoryIndexRoute: typeof AdminAdminInventoryIndexRoute
  AdminAdminOrdersIndexRoute: typeof AdminAdminOrdersIndexRoute
  AdminAdminRepairsIndexRoute: typeof AdminAdminRepairsIndexRoute
  AdminAdminRoomsIndexRoute: typeof AdminAdminRoomsIndexRoute
  AdminAdminSellersIndexRoute: typeof AdminAdminSellersIndexRoute
  AdminAdminStaffIndexRoute: typeof AdminAdminStaffIndexRoute
  AdminAdminStudentsIndexRoute: typeof AdminAdminStudentsIndexRoute
  AdminAdminSuggestionsIndexRoute: typeof AdminAdminSuggestionsIndexRoute
  AdminAdminYellowPagesIndexRoute: typeof AdminAdminYellowPagesIndexRoute
}

const AdminAdminRouteRouteChildren: AdminAdminRouteRouteChildren = {
  AdminAdminAccountRoute: AdminAdminAccountRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminRepairsRequestIdRoute: AdminAdminRepairsRequestIdRoute,
  AdminAdminRoomsUploadRoute: AdminAdminRoomsUploadRoute,
  AdminAdminSellersSellerIdRoute: AdminAdminSellersSellerIdRoute,
  AdminAdminStaffStaffIdRoute: AdminAdminStaffStaffIdRoute,
  AdminAdminStaffNewRoute: AdminAdminStaffNewRoute,
  AdminAdminStudentsStudentIdRoute: AdminAdminStudentsStudentIdRoute,
  AdminAdminAlumniIndexRoute: AdminAdminAlumniIndexRoute,
  AdminAdminEMarketIndexRoute: AdminAdminEMarketIndexRoute,
  AdminAdminFreshmenIndexRoute: AdminAdminFreshmenIndexRoute,
  AdminAdminHubIndexRoute: AdminAdminHubIndexRoute,
  AdminAdminInventoryIndexRoute: AdminAdminInventoryIndexRoute,
  AdminAdminOrdersIndexRoute: AdminAdminOrdersIndexRoute,
  AdminAdminRepairsIndexRoute: AdminAdminRepairsIndexRoute,
  AdminAdminRoomsIndexRoute: AdminAdminRoomsIndexRoute,
  AdminAdminSellersIndexRoute: AdminAdminSellersIndexRoute,
  AdminAdminStaffIndexRoute: AdminAdminStaffIndexRoute,
  AdminAdminStudentsIndexRoute: AdminAdminStudentsIndexRoute,
  AdminAdminSuggestionsIndexRoute: AdminAdminSuggestionsIndexRoute,
  AdminAdminYellowPagesIndexRoute: AdminAdminYellowPagesIndexRoute,
}

const AdminAdminRouteRouteWithChildren = AdminAdminRouteRoute._addFileChildren(
  AdminAdminRouteRouteChildren,
)

interface SellerSellerRouteRouteChildren {
  SellerSellerAccountRoute: typeof SellerSellerAccountRoute
  SellerSellerAnalyticsRoute: typeof SellerSellerAnalyticsRoute
  SellerSellerBillingRoute: typeof SellerSellerBillingRoute
  SellerSellerMenuRoute: typeof SellerSellerMenuRoute
  SellerSellerProductsRoute: typeof SellerSellerProductsRoute
  SellerSellerIndexRoute: typeof SellerSellerIndexRoute
}

const SellerSellerRouteRouteChildren: SellerSellerRouteRouteChildren = {
  SellerSellerAccountRoute: SellerSellerAccountRoute,
  SellerSellerAnalyticsRoute: SellerSellerAnalyticsRoute,
  SellerSellerBillingRoute: SellerSellerBillingRoute,
  SellerSellerMenuRoute: SellerSellerMenuRoute,
  SellerSellerProductsRoute: SellerSellerProductsRoute,
  SellerSellerIndexRoute: SellerSellerIndexRoute,
}

const SellerSellerRouteRouteWithChildren =
  SellerSellerRouteRoute._addFileChildren(SellerSellerRouteRouteChildren)

interface StudentStudentRouteRouteChildren {
  StudentStudentProfileRoute: typeof StudentStudentProfileRoute
  StudentStudentSuggestionsRoute: typeof StudentStudentSuggestionsRoute
  StudentStudentIndexRoute: typeof StudentStudentIndexRoute
  StudentStudentOrdersNewRoute: typeof StudentStudentOrdersNewRoute
  StudentStudentRepairsNewRoute: typeof StudentStudentRepairsNewRoute
  StudentStudentOrdersIndexRoute: typeof StudentStudentOrdersIndexRoute
  StudentStudentRepairsIndexRoute: typeof StudentStudentRepairsIndexRoute
}

const StudentStudentRouteRouteChildren: StudentStudentRouteRouteChildren = {
  StudentStudentProfileRoute: StudentStudentProfileRoute,
  StudentStudentSuggestionsRoute: StudentStudentSuggestionsRoute,
  StudentStudentIndexRoute: StudentStudentIndexRoute,
  StudentStudentOrdersNewRoute: StudentStudentOrdersNewRoute,
  StudentStudentRepairsNewRoute: StudentStudentRepairsNewRoute,
  StudentStudentOrdersIndexRoute: StudentStudentOrdersIndexRoute,
  StudentStudentRepairsIndexRoute: StudentStudentRepairsIndexRoute,
}

const StudentStudentRouteRouteWithChildren =
  StudentStudentRouteRoute._addFileChildren(StudentStudentRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  WebRouteRoute: WebRouteRouteWithChildren,
  AdminAdminRouteRoute: AdminAdminRouteRouteWithChildren,
  SellerSellerRouteRoute: SellerSellerRouteRouteWithChildren,
  StudentStudentRouteRoute: StudentStudentRouteRouteWithChildren,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  SellerLoginRoute: SellerLoginRoute,
  SellerRegisterRoute: SellerRegisterRoute,
  StudentForgotPinRoute: StudentForgotPinRoute,
  StudentLoginRoute: StudentLoginRoute,
  PrintInventoryRequestIdRoute: PrintInventoryRequestIdRoute,
  PrintRepairsRequestIdRoute: PrintRepairsRequestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
