/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebRouteRouteImport } from './routes/_web/route'
import { Route as WebIndexRouteImport } from './routes/_web/index'
import { Route as WebRegisterRouteImport } from './routes/_web/register'
import { Route as AdminAdminRouteRouteImport } from './routes/admin/_admin/route'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as StudentStudentRouteRouteImport } from './routes/student/_student/route'
import { Route as StudentForgotPinRouteImport } from './routes/student/forgot-pin'
import { Route as StudentLoginRouteImport } from './routes/student/login'
import { Route as AdminAdminIndexRouteImport } from './routes/admin/_admin/index'
import { Route as AdminAdminAccountRouteImport } from './routes/admin/_admin/account'
import { Route as AdminAdminReportsRouteImport } from './routes/admin/_admin/reports'
import { Route as StudentStudentIndexRouteImport } from './routes/student/_student/index'
import { Route as StudentStudentProfileRouteImport } from './routes/student/_student/profile'
import { Route as StudentStudentSuggestionsRouteImport } from './routes/student/_student/suggestions'
import { Route as AdminAdminOrdersIndexRouteImport } from './routes/admin/_admin/orders/index'
import { Route as AdminAdminRepairsIndexRouteImport } from './routes/admin/_admin/repairs/index'
import { Route as AdminAdminRepairsRequestIdRouteImport } from './routes/admin/_admin/repairs/$requestId'
import { Route as AdminAdminRoomsIndexRouteImport } from './routes/admin/_admin/rooms/index'
import { Route as AdminAdminRoomsUploadRouteImport } from './routes/admin/_admin/rooms/upload'
import { Route as AdminAdminStaffIndexRouteImport } from './routes/admin/_admin/staff/index'
import { Route as AdminAdminStaffStaffIdRouteImport } from './routes/admin/_admin/staff/$staffId'
import { Route as AdminAdminStaffNewRouteImport } from './routes/admin/_admin/staff/new'
import { Route as AdminAdminStudentsIndexRouteImport } from './routes/admin/_admin/students/index'
import { Route as AdminAdminStudentsStudentIdRouteImport } from './routes/admin/_admin/students/$studentId'
import { Route as AdminAdminSuggestionsIndexRouteImport } from './routes/admin/_admin/suggestions/index'
import { Route as StudentStudentOrdersIndexRouteImport } from './routes/student/_student/orders/index'
import { Route as StudentStudentOrdersNewRouteImport } from './routes/student/_student/orders/new'
import { Route as StudentStudentRepairsIndexRouteImport } from './routes/student/_student/repairs/index'
import { Route as StudentStudentRepairsNewRouteImport } from './routes/student/_student/repairs/new'

const WebRouteRoute = WebRouteRouteImport.update({
  id: '/_web',
  getParentRoute: () => rootRouteImport,
} as any)
const WebIndexRoute = WebIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebRouteRoute,
} as any)
const WebRegisterRoute = WebRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => WebRouteRoute,
} as any)
const AdminAdminRouteRoute = AdminAdminRouteRouteImport.update({
  id: '/admin/_admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStudentRouteRoute = StudentStudentRouteRouteImport.update({
  id: '/student/_student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentForgotPinRoute = StudentForgotPinRouteImport.update({
  id: '/student/forgot-pin',
  path: '/student/forgot-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminAccountRoute = AdminAdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const StudentStudentIndexRoute = StudentStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentStudentRouteRoute,
} as any)
const StudentStudentProfileRoute = StudentStudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentStudentRouteRoute,
} as any)
const StudentStudentSuggestionsRoute =
  StudentStudentSuggestionsRouteImport.update({
    id: '/suggestions',
    path: '/suggestions',
    getParentRoute: () => StudentStudentRouteRoute,
  } as any)
const AdminAdminOrdersIndexRoute = AdminAdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminRepairsIndexRoute = AdminAdminRepairsIndexRouteImport.update({
  id: '/repairs/',
  path: '/repairs/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminRepairsRequestIdRoute =
  AdminAdminRepairsRequestIdRouteImport.update({
    id: '/repairs/$requestId',
    path: '/repairs/$requestId',
    getParentRoute: () => AdminAdminRouteRoute,
  } as any)
const AdminAdminRoomsIndexRoute = AdminAdminRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminRoomsUploadRoute = AdminAdminRoomsUploadRouteImport.update({
  id: '/rooms/upload',
  path: '/rooms/upload',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminStaffIndexRoute = AdminAdminStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminStaffStaffIdRoute = AdminAdminStaffStaffIdRouteImport.update({
  id: '/staff/$staffId',
  path: '/staff/$staffId',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminStaffNewRoute = AdminAdminStaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminStudentsIndexRoute = AdminAdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminStudentsStudentIdRoute =
  AdminAdminStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AdminAdminRouteRoute,
  } as any)
const AdminAdminSuggestionsIndexRoute =
  AdminAdminSuggestionsIndexRouteImport.update({
    id: '/suggestions/',
    path: '/suggestions/',
    getParentRoute: () => AdminAdminRouteRoute,
  } as any)
const StudentStudentOrdersIndexRoute =
  StudentStudentOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => StudentStudentRouteRoute,
  } as any)
const StudentStudentOrdersNewRoute = StudentStudentOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => StudentStudentRouteRoute,
} as any)
const StudentStudentRepairsIndexRoute =
  StudentStudentRepairsIndexRouteImport.update({
    id: '/repairs/',
    path: '/repairs/',
    getParentRoute: () => StudentStudentRouteRoute,
  } as any)
const StudentStudentRepairsNewRoute =
  StudentStudentRepairsNewRouteImport.update({
    id: '/repairs/new',
    path: '/repairs/new',
    getParentRoute: () => StudentStudentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WebIndexRoute
  '/admin': typeof AdminAdminRouteRouteWithChildren
  '/student': typeof StudentStudentRouteRouteWithChildren
  '/register': typeof WebRegisterRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/student/forgot-pin': typeof StudentForgotPinRoute
  '/student/login': typeof StudentLoginRoute
  '/admin/account': typeof AdminAdminAccountRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/student/profile': typeof StudentStudentProfileRoute
  '/student/suggestions': typeof StudentStudentSuggestionsRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/student/': typeof StudentStudentIndexRoute
  '/admin/repairs/$requestId': typeof AdminAdminRepairsRequestIdRoute
  '/admin/rooms/upload': typeof AdminAdminRoomsUploadRoute
  '/admin/staff/$staffId': typeof AdminAdminStaffStaffIdRoute
  '/admin/staff/new': typeof AdminAdminStaffNewRoute
  '/admin/students/$studentId': typeof AdminAdminStudentsStudentIdRoute
  '/student/orders/new': typeof StudentStudentOrdersNewRoute
  '/student/repairs/new': typeof StudentStudentRepairsNewRoute
  '/admin/orders/': typeof AdminAdminOrdersIndexRoute
  '/admin/repairs/': typeof AdminAdminRepairsIndexRoute
  '/admin/rooms/': typeof AdminAdminRoomsIndexRoute
  '/admin/staff/': typeof AdminAdminStaffIndexRoute
  '/admin/students/': typeof AdminAdminStudentsIndexRoute
  '/admin/suggestions/': typeof AdminAdminSuggestionsIndexRoute
  '/student/orders/': typeof StudentStudentOrdersIndexRoute
  '/student/repairs/': typeof StudentStudentRepairsIndexRoute
}
export interface FileRoutesByTo {
  '/register': typeof WebRegisterRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/student/forgot-pin': typeof StudentForgotPinRoute
  '/student/login': typeof StudentLoginRoute
  '/': typeof WebIndexRoute
  '/admin/account': typeof AdminAdminAccountRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/student/profile': typeof StudentStudentProfileRoute
  '/student/suggestions': typeof StudentStudentSuggestionsRoute
  '/admin': typeof AdminAdminIndexRoute
  '/student': typeof StudentStudentIndexRoute
  '/admin/repairs/$requestId': typeof AdminAdminRepairsRequestIdRoute
  '/admin/rooms/upload': typeof AdminAdminRoomsUploadRoute
  '/admin/staff/$staffId': typeof AdminAdminStaffStaffIdRoute
  '/admin/staff/new': typeof AdminAdminStaffNewRoute
  '/admin/students/$studentId': typeof AdminAdminStudentsStudentIdRoute
  '/student/orders/new': typeof StudentStudentOrdersNewRoute
  '/student/repairs/new': typeof StudentStudentRepairsNewRoute
  '/admin/orders': typeof AdminAdminOrdersIndexRoute
  '/admin/repairs': typeof AdminAdminRepairsIndexRoute
  '/admin/rooms': typeof AdminAdminRoomsIndexRoute
  '/admin/staff': typeof AdminAdminStaffIndexRoute
  '/admin/students': typeof AdminAdminStudentsIndexRoute
  '/admin/suggestions': typeof AdminAdminSuggestionsIndexRoute
  '/student/orders': typeof StudentStudentOrdersIndexRoute
  '/student/repairs': typeof StudentStudentRepairsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_web': typeof WebRouteRouteWithChildren
  '/admin/_admin': typeof AdminAdminRouteRouteWithChildren
  '/student/_student': typeof StudentStudentRouteRouteWithChildren
  '/_web/register': typeof WebRegisterRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/student/forgot-pin': typeof StudentForgotPinRoute
  '/student/login': typeof StudentLoginRoute
  '/_web/': typeof WebIndexRoute
  '/admin/_admin/account': typeof AdminAdminAccountRoute
  '/admin/_admin/reports': typeof AdminAdminReportsRoute
  '/student/_student/profile': typeof StudentStudentProfileRoute
  '/student/_student/suggestions': typeof StudentStudentSuggestionsRoute
  '/admin/_admin/': typeof AdminAdminIndexRoute
  '/student/_student/': typeof StudentStudentIndexRoute
  '/admin/_admin/repairs/$requestId': typeof AdminAdminRepairsRequestIdRoute
  '/admin/_admin/rooms/upload': typeof AdminAdminRoomsUploadRoute
  '/admin/_admin/staff/$staffId': typeof AdminAdminStaffStaffIdRoute
  '/admin/_admin/staff/new': typeof AdminAdminStaffNewRoute
  '/admin/_admin/students/$studentId': typeof AdminAdminStudentsStudentIdRoute
  '/student/_student/orders/new': typeof StudentStudentOrdersNewRoute
  '/student/_student/repairs/new': typeof StudentStudentRepairsNewRoute
  '/admin/_admin/orders/': typeof AdminAdminOrdersIndexRoute
  '/admin/_admin/repairs/': typeof AdminAdminRepairsIndexRoute
  '/admin/_admin/rooms/': typeof AdminAdminRoomsIndexRoute
  '/admin/_admin/staff/': typeof AdminAdminStaffIndexRoute
  '/admin/_admin/students/': typeof AdminAdminStudentsIndexRoute
  '/admin/_admin/suggestions/': typeof AdminAdminSuggestionsIndexRoute
  '/student/_student/orders/': typeof StudentStudentOrdersIndexRoute
  '/student/_student/repairs/': typeof StudentStudentRepairsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/register'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/api/$'
    | '/student/forgot-pin'
    | '/student/login'
    | '/admin/account'
    | '/admin/reports'
    | '/student/profile'
    | '/student/suggestions'
    | '/admin/'
    | '/student/'
    | '/admin/repairs/$requestId'
    | '/admin/rooms/upload'
    | '/admin/staff/$staffId'
    | '/admin/staff/new'
    | '/admin/students/$studentId'
    | '/student/orders/new'
    | '/student/repairs/new'
    | '/admin/orders/'
    | '/admin/repairs/'
    | '/admin/rooms/'
    | '/admin/staff/'
    | '/admin/students/'
    | '/admin/suggestions/'
    | '/student/orders/'
    | '/student/repairs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/register'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/api/$'
    | '/student/forgot-pin'
    | '/student/login'
    | '/'
    | '/admin/account'
    | '/admin/reports'
    | '/student/profile'
    | '/student/suggestions'
    | '/admin'
    | '/student'
    | '/admin/repairs/$requestId'
    | '/admin/rooms/upload'
    | '/admin/staff/$staffId'
    | '/admin/staff/new'
    | '/admin/students/$studentId'
    | '/student/orders/new'
    | '/student/repairs/new'
    | '/admin/orders'
    | '/admin/repairs'
    | '/admin/rooms'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/suggestions'
    | '/student/orders'
    | '/student/repairs'
  id:
    | '__root__'
    | '/_web'
    | '/admin/_admin'
    | '/student/_student'
    | '/_web/register'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/api/$'
    | '/student/forgot-pin'
    | '/student/login'
    | '/_web/'
    | '/admin/_admin/account'
    | '/admin/_admin/reports'
    | '/student/_student/profile'
    | '/student/_student/suggestions'
    | '/admin/_admin/'
    | '/student/_student/'
    | '/admin/_admin/repairs/$requestId'
    | '/admin/_admin/rooms/upload'
    | '/admin/_admin/staff/$staffId'
    | '/admin/_admin/staff/new'
    | '/admin/_admin/students/$studentId'
    | '/student/_student/orders/new'
    | '/student/_student/repairs/new'
    | '/admin/_admin/orders/'
    | '/admin/_admin/repairs/'
    | '/admin/_admin/rooms/'
    | '/admin/_admin/staff/'
    | '/admin/_admin/students/'
    | '/admin/_admin/suggestions/'
    | '/student/_student/orders/'
    | '/student/_student/repairs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WebRouteRoute: typeof WebRouteRouteWithChildren
  AdminAdminRouteRoute: typeof AdminAdminRouteRouteWithChildren
  StudentStudentRouteRoute: typeof StudentStudentRouteRouteWithChildren
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  StudentForgotPinRoute: typeof StudentForgotPinRoute
  StudentLoginRoute: typeof StudentLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_web': {
      id: '/_web'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WebRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web/': {
      id: '/_web/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebIndexRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/_web/register': {
      id: '/_web/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof WebRegisterRouteImport
      parentRoute: typeof WebRouteRoute
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/_student': {
      id: '/student/_student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentStudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/forgot-pin': {
      id: '/student/forgot-pin'
      path: '/student/forgot-pin'
      fullPath: '/student/forgot-pin'
      preLoaderRoute: typeof StudentForgotPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin/': {
      id: '/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/account': {
      id: '/admin/_admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAdminAccountRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/reports': {
      id: '/admin/_admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/student/_student/': {
      id: '/student/_student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentStudentIndexRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
    '/student/_student/profile': {
      id: '/student/_student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentStudentProfileRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
    '/student/_student/suggestions': {
      id: '/student/_student/suggestions'
      path: '/suggestions'
      fullPath: '/student/suggestions'
      preLoaderRoute: typeof StudentStudentSuggestionsRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
    '/admin/_admin/orders/': {
      id: '/admin/_admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminAdminOrdersIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/repairs/': {
      id: '/admin/_admin/repairs/'
      path: '/repairs'
      fullPath: '/admin/repairs/'
      preLoaderRoute: typeof AdminAdminRepairsIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/repairs/$requestId': {
      id: '/admin/_admin/repairs/$requestId'
      path: '/repairs/$requestId'
      fullPath: '/admin/repairs/$requestId'
      preLoaderRoute: typeof AdminAdminRepairsRequestIdRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/rooms/': {
      id: '/admin/_admin/rooms/'
      path: '/rooms'
      fullPath: '/admin/rooms/'
      preLoaderRoute: typeof AdminAdminRoomsIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/rooms/upload': {
      id: '/admin/_admin/rooms/upload'
      path: '/rooms/upload'
      fullPath: '/admin/rooms/upload'
      preLoaderRoute: typeof AdminAdminRoomsUploadRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/staff/': {
      id: '/admin/_admin/staff/'
      path: '/staff'
      fullPath: '/admin/staff/'
      preLoaderRoute: typeof AdminAdminStaffIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/staff/$staffId': {
      id: '/admin/_admin/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/admin/staff/$staffId'
      preLoaderRoute: typeof AdminAdminStaffStaffIdRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/staff/new': {
      id: '/admin/_admin/staff/new'
      path: '/staff/new'
      fullPath: '/admin/staff/new'
      preLoaderRoute: typeof AdminAdminStaffNewRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/students/': {
      id: '/admin/_admin/students/'
      path: '/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AdminAdminStudentsIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/students/$studentId': {
      id: '/admin/_admin/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AdminAdminStudentsStudentIdRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/suggestions/': {
      id: '/admin/_admin/suggestions/'
      path: '/suggestions'
      fullPath: '/admin/suggestions/'
      preLoaderRoute: typeof AdminAdminSuggestionsIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/student/_student/orders/': {
      id: '/student/_student/orders/'
      path: '/orders'
      fullPath: '/student/orders/'
      preLoaderRoute: typeof StudentStudentOrdersIndexRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
    '/student/_student/orders/new': {
      id: '/student/_student/orders/new'
      path: '/orders/new'
      fullPath: '/student/orders/new'
      preLoaderRoute: typeof StudentStudentOrdersNewRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
    '/student/_student/repairs/': {
      id: '/student/_student/repairs/'
      path: '/repairs'
      fullPath: '/student/repairs/'
      preLoaderRoute: typeof StudentStudentRepairsIndexRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
    '/student/_student/repairs/new': {
      id: '/student/_student/repairs/new'
      path: '/repairs/new'
      fullPath: '/student/repairs/new'
      preLoaderRoute: typeof StudentStudentRepairsNewRouteImport
      parentRoute: typeof StudentStudentRouteRoute
    }
  }
}

interface WebRouteRouteChildren {
  WebRegisterRoute: typeof WebRegisterRoute
  WebIndexRoute: typeof WebIndexRoute
}

const WebRouteRouteChildren: WebRouteRouteChildren = {
  WebRegisterRoute: WebRegisterRoute,
  WebIndexRoute: WebIndexRoute,
}

const WebRouteRouteWithChildren = WebRouteRoute._addFileChildren(
  WebRouteRouteChildren,
)

interface AdminAdminRouteRouteChildren {
  AdminAdminAccountRoute: typeof AdminAdminAccountRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminRepairsRequestIdRoute: typeof AdminAdminRepairsRequestIdRoute
  AdminAdminRoomsUploadRoute: typeof AdminAdminRoomsUploadRoute
  AdminAdminStaffStaffIdRoute: typeof AdminAdminStaffStaffIdRoute
  AdminAdminStaffNewRoute: typeof AdminAdminStaffNewRoute
  AdminAdminStudentsStudentIdRoute: typeof AdminAdminStudentsStudentIdRoute
  AdminAdminOrdersIndexRoute: typeof AdminAdminOrdersIndexRoute
  AdminAdminRepairsIndexRoute: typeof AdminAdminRepairsIndexRoute
  AdminAdminRoomsIndexRoute: typeof AdminAdminRoomsIndexRoute
  AdminAdminStaffIndexRoute: typeof AdminAdminStaffIndexRoute
  AdminAdminStudentsIndexRoute: typeof AdminAdminStudentsIndexRoute
  AdminAdminSuggestionsIndexRoute: typeof AdminAdminSuggestionsIndexRoute
}

const AdminAdminRouteRouteChildren: AdminAdminRouteRouteChildren = {
  AdminAdminAccountRoute: AdminAdminAccountRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminRepairsRequestIdRoute: AdminAdminRepairsRequestIdRoute,
  AdminAdminRoomsUploadRoute: AdminAdminRoomsUploadRoute,
  AdminAdminStaffStaffIdRoute: AdminAdminStaffStaffIdRoute,
  AdminAdminStaffNewRoute: AdminAdminStaffNewRoute,
  AdminAdminStudentsStudentIdRoute: AdminAdminStudentsStudentIdRoute,
  AdminAdminOrdersIndexRoute: AdminAdminOrdersIndexRoute,
  AdminAdminRepairsIndexRoute: AdminAdminRepairsIndexRoute,
  AdminAdminRoomsIndexRoute: AdminAdminRoomsIndexRoute,
  AdminAdminStaffIndexRoute: AdminAdminStaffIndexRoute,
  AdminAdminStudentsIndexRoute: AdminAdminStudentsIndexRoute,
  AdminAdminSuggestionsIndexRoute: AdminAdminSuggestionsIndexRoute,
}

const AdminAdminRouteRouteWithChildren = AdminAdminRouteRoute._addFileChildren(
  AdminAdminRouteRouteChildren,
)

interface StudentStudentRouteRouteChildren {
  StudentStudentProfileRoute: typeof StudentStudentProfileRoute
  StudentStudentSuggestionsRoute: typeof StudentStudentSuggestionsRoute
  StudentStudentIndexRoute: typeof StudentStudentIndexRoute
  StudentStudentOrdersNewRoute: typeof StudentStudentOrdersNewRoute
  StudentStudentRepairsNewRoute: typeof StudentStudentRepairsNewRoute
  StudentStudentOrdersIndexRoute: typeof StudentStudentOrdersIndexRoute
  StudentStudentRepairsIndexRoute: typeof StudentStudentRepairsIndexRoute
}

const StudentStudentRouteRouteChildren: StudentStudentRouteRouteChildren = {
  StudentStudentProfileRoute: StudentStudentProfileRoute,
  StudentStudentSuggestionsRoute: StudentStudentSuggestionsRoute,
  StudentStudentIndexRoute: StudentStudentIndexRoute,
  StudentStudentOrdersNewRoute: StudentStudentOrdersNewRoute,
  StudentStudentRepairsNewRoute: StudentStudentRepairsNewRoute,
  StudentStudentOrdersIndexRoute: StudentStudentOrdersIndexRoute,
  StudentStudentRepairsIndexRoute: StudentStudentRepairsIndexRoute,
}

const StudentStudentRouteRouteWithChildren =
  StudentStudentRouteRoute._addFileChildren(StudentStudentRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  WebRouteRoute: WebRouteRouteWithChildren,
  AdminAdminRouteRoute: AdminAdminRouteRouteWithChildren,
  StudentStudentRouteRoute: StudentStudentRouteRouteWithChildren,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  StudentForgotPinRoute: StudentForgotPinRoute,
  StudentLoginRoute: StudentLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
