CREATE TABLE IF NOT EXISTS students (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  room_id INT UNSIGNED NOT NULL,
  gender ENUM('male', 'female') NOT NULL,
  full_name VARCHAR(150) NOT NULL,
  registration_number VARCHAR(30) NOT NULL,
  programme VARCHAR(150) NOT NULL,
  level ENUM('100', '200', '300', '400', '500', '600') NOT NULL,
  phone_country_code VARCHAR(5) NOT NULL DEFAULT '+233',
  phone_number VARCHAR(20) NOT NULL,
  passport_photo_url VARCHAR(500) NOT NULL,
  emergency_contact_name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL,
  emergency_contact_number VARCHAR(20) NOT NULL,
  id_type ENUM('ghana_card', 'passport') NOT NULL,
  id_number VARCHAR(50) NOT NULL,
  receipt_url VARCHAR(500) NOT NULL,
  pin_hash VARCHAR(255) NOT NULL,
  failed_pin_attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
  locked_until DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_students_registration_number (registration_number),
  UNIQUE KEY uq_students_email (email),
  KEY idx_students_room_id (room_id),
  CONSTRAINT fk_students_room FOREIGN KEY (room_id) REFERENCES rooms (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
