CREATE TABLE IF NOT EXISTS food_vendors (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(150) NOT NULL,
  cuisine VARCHAR(100) NULL,
  description VARCHAR(500) NULL,
  logo_url VARCHAR(500) NULL,
  phone VARCHAR(30) NULL,
  location VARCHAR(255) NULL,
  opening_hours VARCHAR(150) NULL,
  delivers TINYINT(1) NOT NULL DEFAULT 0,
  is_open TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
