CREATE TABLE IF NOT EXISTS sellers (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  seller_type ENUM('business', 'food_vendor') NOT NULL,
  business_name VARCHAR(150) NOT NULL,
  owner_name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  location VARCHAR(255) NULL,
  description VARCHAR(500) NULL,
  password_hash VARCHAR(255) NOT NULL,
  status ENUM('pending', 'approved', 'rejected', 'suspended') NOT NULL DEFAULT 'pending',
  status_reason VARCHAR(500) NULL,
  reviewed_by INT UNSIGNED NULL,
  reviewed_at DATETIME NULL,
  registration_paid_at DATETIME NULL,
  paid_until DATE NULL,
  failed_login_attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
  locked_until DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_sellers_email (email),
  KEY idx_sellers_status (status),
  CONSTRAINT fk_sellers_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES admins (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
