CREATE TABLE IF NOT EXISTS hub_posts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  type ENUM('spotlight', 'announcement', 'news', 'event') NOT NULL,
  title VARCHAR(255) NOT NULL,
  excerpt VARCHAR(1000) NULL,
  body TEXT NULL,
  category VARCHAR(60) NULL,
  category_url VARCHAR(500) NULL,
  link_url VARCHAR(500) NULL,
  image_url VARCHAR(500) NULL,
  published_on DATE NOT NULL,
  event_start DATE NULL,
  event_end DATE NULL,
  event_time VARCHAR(60) NULL,
  location VARCHAR(255) NULL,
  is_featured TINYINT(1) NOT NULL DEFAULT 0,
  is_published TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_hub_posts_type (type, is_published, published_on),
  CONSTRAINT fk_hub_posts_created_by FOREIGN KEY (created_by) REFERENCES admins (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
