CREATE TABLE IF NOT EXISTS freshmen_sections (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  guide_id INT UNSIGNED NOT NULL,
  title VARCHAR(150) NOT NULL,
  intro MEDIUMTEXT NULL,
  image_url VARCHAR(500) NULL,
  is_mandatory TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  is_published TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_freshmen_sections_guide (guide_id, sort_order),
  CONSTRAINT fk_freshmen_sections_guide FOREIGN KEY (guide_id) REFERENCES freshmen_guides (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
