CREATE TABLE IF NOT EXISTS alumni_projects (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(150) NOT NULL,
  summary VARCHAR(500) NULL,
  category VARCHAR(60) NULL,
  status ENUM('planned', 'ongoing', 'completed') NOT NULL DEFAULT 'ongoing',
  goal_amount DECIMAL(12, 2) NULL,
  image_url VARCHAR(500) NULL,
  led_by VARCHAR(150) NULL,
  year_label VARCHAR(40) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_published TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
