CREATE TABLE IF NOT EXISTS alumni_executives (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(150) NOT NULL,
  position VARCHAR(150) NOT NULL,
  class_year VARCHAR(40) NULL,
  bio VARCHAR(500) NULL,
  photo_url VARCHAR(500) NULL,
  email VARCHAR(150) NULL,
  phone VARCHAR(30) NULL,
  linkedin_url VARCHAR(500) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
