CREATE TABLE IF NOT EXISTS alumni_donation_channels (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  type ENUM('momo', 'bank', 'card', 'other') NOT NULL,
  label VARCHAR(100) NOT NULL,
  account_name VARCHAR(150) NULL,
  account_number VARCHAR(60) NULL,
  provider VARCHAR(100) NULL,
  branch VARCHAR(100) NULL,
  link_url VARCHAR(500) NULL,
  instructions VARCHAR(500) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
